ci(sonar): update jacoco url

diff --git a/.github/workflows/sonar-quality-gate.yml b/.github/workflows/sonar-quality-gate.yml
--- a/.github/workflows/sonar-quality-gate.yml
+++ b/.github/workflows/sonar-quality-gate.yml
@@ -11,7 +11,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
+        with:
+          fetch-depth: 0
       - name: Set up JDK 23
         uses: actions/setup-java@v4
         with:
@@ -26,15 +27,21 @@ jobs:
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
 
-      - name: Build and test with Maven
-        run: mvn -B clean verify
-
       - name: Sonar scan
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
-          -Dsonar.projectKey=giovannilramos_movie-randomizer-api \
-          -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco/jacoco.xml \
-          -Dsonar.branch.name=main
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=giovannilramos_movie-randomizer-api -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco/jacoco.xml
 
+      - name: Check Quality Gate status
+        run: |
+          PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F '/' '{print $NF}')
+          sleep 15
+          QUALITY_GATE_STATUS=$(curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=giovannilramos_movie-randomizer-api&pullRequest=$PR_NUMBER" | jq -r '.projectStatus.status')
+          
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "Quality Gate did not pass. Exiting with failure."
+            exit 1
+          else
+            echo "Quality Gate passed."
+          fi
